### ISSUE TITLE
Create Workflow for Dante and test

### ISSUE THREAD

**Issue by kriziaf** [Emceelamb/itp-help-site#4]
1. Recreate this page: http://help.itp.nyu.edu/curriculum/registration/spring-2019-reg-info

2. @karihigh and I will meet with Dante on 3/13 to show him the workflow and test if it works, get his feedback.

**Comment by kriziaf** [comment]
Started 3/13

**Comment by kriziaf** [comment]
Updates:

1. Registration pages 
 - Dante agreed to recreate screenshare audio descriptions for all instructional content that has screenshots
 - We have to recreate a ITP Help Youtube account to house the screenshares, Krizia to e-mail Yen
- We found Albert How-to content  (Add/Drop)that exists on NYU's  - @karihigh to share link
 - Ideally, to finish the site by 4/15 ready for Fall Registration

**Comment by karihigh** [comment]
Dante's Fall registration video is ready and uploaded.
