### ISSUE TITLE
What about using Markdown in the wordpress sites? 

### ISSUE THREAD

**Issue by karihigh** [Emceelamb/itp-help-site#7]
https://wordpress.org/plugins/wp-markdown/

**Comment by Emceelamb** [comment]
I think this is something to ask the content editors. While I also like markdown I feel like most people don't use markdown and learning md syntax is an unnecessary step for the average editor.

**Comment by kriziaf** [comment]
@Emceelamb agree - I guess I will use slack next time for internal design questions like this! #pleaseclose
